### ISSUE TITLE
你好 如何在二三级页面创建组件或者vue页面

### ISSUE THREAD

**Issue by z937010871** [seanyujc/sgv-cli#1]
你好,请教下老师,如何在pages页面下创建二三级页面呢

**Comment by seanyujc** [comment]
暂时没有此功能。可先建一级页，然后自己改路由配置。

**Comment by seanyujc** [comment]
更新版本，现在你可以使用斜杠分割创建名的形式来创建多级页面，如“sgv build -p news/list“。
